name: Hydra Dragon IP Scan
on:
  schedule:
    - cron: '0 */1 * * *' # Runs every hour
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  scan-and-report:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Hydra Scanner
        run: python antivirus.py

      - name: Run Post-Scan Filter
        run: python post_script.py

      - name: Commit and push reports
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add website/reports/*.csv
          git add logs/*.log
          git commit -m "Automated Threat Intelligence Report Update" || echo "No changes to commit"
          git push
